---
version: '3'
services:
  promhouse:
    container_name: promhouse
    image: golang
    ports:
      - 127:0.0.1:7781:7781
      - 127:0.0.1:7782:7782
    network_mode: host
    volumes:
      - ./promhouse_bin:/promhouse_bin
      - ./waitforit.sh:/waitforit.sh
    entrypoint: "/waitforit.sh -s -t 30 -h 127.0.0.1 -p 9000 -- /promhouse_bin --log.level=info"
    depends_on:
      - grafana
      - prometheus
      - clickhouse_exporter
      - clickhouse
      - node_exporter
    deploy:
      resources:
        limits:
          memory: 2.5G
