# tools
required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gogo",
]

[prune]
  go-tests = true
  unused-packages = true

  # to keep gogo.proto
  # non-go = true
